apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-flz0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-flz0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-flz0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-flz0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-flz0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vkns-tenant/rhtap-demo-app/hacbs-test-project-flz0@sha256:9807444392483966d48354dc92856e24fb75ca2c8f033966b7ff5d70a41f86b7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
