apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-flz0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vkns-tenant/rhtap-demo-app/hacbs-test-project-flz0@sha256:455125710278d6b4de50279221c457524b3be4436d210f3d7ed616ef91125082
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
